import type { Person, Zone } from "./types";

export const DEFAULT_PEOPLE: Person[] = [
  { id: "kdh", name: "김도헌" },
  { id: "rjk", name: "류제경" },
  { id: "bhj", name: "방효정" },
  { id: "jih", name: "박지환" },
  { id: "pms", name: "박민성" },
  { id: "psm", name: "박상민" },
  { id: "pjy", name: "박준영" },
  { id: "ygw", name: "윤건우" },
  { id: "isj", name: "임성재" },
  { id: "lss", name: "이승섭" },
  { id: "lsy", name: "이승윤" },
  { id: "chs", name: "조현성" },
  { id: "cse", name: "최세인" },
  { id: "csm", name: "최성민" },
];

export const DEFAULT_ZONES: Zone[] = [
  { id: "zone01", label: "당직사관실" },
  { id: "zone02", label: "청소도구" },
  { id: "zone03", label: "상담실" },
  { id: "zone04", label: "중동아리방" },
  { id: "zone05", label: "사지방(1)" },
  { id: "zone06", label: "사지방(2)" },
  { id: "zone07", label: "독서실" },
  { id: "zone08", label: "체단실(1)" },
  { id: "zone09", label: "체단실(2)" },
  { id: "zone10", label: "휴게실(1)" },
  { id: "zone11", label: "휴게실(2)" },
  { id: "zone12", label: "복도3 생걸" },
  { id: "zone13", label: "복도3 우중걸" },
  { id: "zone14", label: "복도3 우중빗" },
  { id: "zone15", label: "복도3 좌중걸" },
  { id: "zone16", label: "복도3 좌중빗" },
  { id: "zone17", label: "우계단 걸" },
  { id: "zone18", label: "우계단 빗" },
  { id: "zone19", label: "좌계단 걸" },
  { id: "zone20", label: "좌계단 빗" },
  { id: "zone21", label: "중계단 걸" },
  { id: "zone22", label: "중계단 빗" },
  { id: "zone23", label: "복도2 생걸" },
  { id: "zone24", label: "복도2 우중걸" },
  { id: "zone25", label: "복도2 우중빗" },
  { id: "zone26", label: "복도2 좌중걸" },
  { id: "zone27", label: "복도2 좌중빗" },
  { id: "zone28", label: "전자레인지" },
  { id: "zone29", label: "우건조기" },
  { id: "zone30", label: "좌건조기" },
  { id: "zone31", label: "샤워장(1)" },
  { id: "zone32", label: "샤워장(2)" },
  { id: "zone33", label: "샤워장(3)" },
  { id: "zone34", label: "우화3(1)" },
  { id: "zone35", label: "우화3(2)" },
  { id: "zone36", label: "우화3(3)" },
  { id: "zone37", label: "우화3(4)" },
  { id: "zone38", label: "좌화3(1)" },
  { id: "zone39", label: "좌화3(2)" },
  { id: "zone40", label: "좌화3(3)" },
  { id: "zone41", label: "좌화3(4)" },
];
